site_name: Работилничка документација

#site_url: https://itaseski.github.io/mkdocs-workshop/

theme:
  name: material
  # Changing the colors
  palette:
    primary: green
    accent: light green
  # Changing the fonts
  font:
    text: Roboto
    code: Roboto Mono 
  # Site language
  language: mk
  # Logo
  logo: assets/logo.png
  # Favicon
  favicon: images/favicon.png
  # Icons
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16 
  # Features
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.sections
    #- navigation.indexes 
    - toc.follow
    #- toc.integrate
    - content.tabs.link
    #- header.autohide
    - search.suggest
    - search.highlight
    - search.share    
    #- navigation.expand
    - navigation.top

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons  

plugins:
  - search:
      lang: mk
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100vh       
       height: auto
       zoomable: true
       draggable: true
       skip_classes: 
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom 


extra_css:
  - stylesheets/extra.css


#repo_url: https://github.com/itaseski/mkdocs-workshop.git

# navigation
nav:
  - Општо:
    - Возило комплет:
      - Поправка на пластични делови: vehicle/000001.md  
      - Складирање на шасии и делови: vehicle/000002.md 
      - Означување: vehicle/000003.md
      - Вибрации: vehicle/000004.md
    - Инструкции:
      - Влечење и пренесување: vehicle/000105.md
      - Споеви со завртки: vehicle/000106.md
      - Единици мерки: vehicle/000107.md
  - Мотор:
    - Перење на моторот: engine/010001.md
  - Систем за ладење:
    - Систем за ладење склоп:
      - Систем за ладење: cooling-system/020001.md
    - Ладилник:
      - Експанзионен резервоар: cooling-system/020101.md
      - Ладилник: cooling-system/020102.md
    - Ладилник за напоен воздух:
        - Ладилник за напоен воздух: cooling-system/020501.md
        - T121, сензор за температура на напојниот воздух: cooling-system/020502.md
        - T122, сензор за притисок на напојниот воздух: cooling-system/020503.md
  - Гориво и издувни гасови:
    - Систем за гориво склоп:
      - Пресметка на факторот на потрошувачка на гориво: fuel/030001.md
      - Гориво: fuel/030002.md
      - Систем за гориво Scania XPI: fuel/030003.md
    - Бризгалки:
      - Акумулатор: fuel/030101.md
      - Напојна пумпа: fuel/030102.md
      - Бризгалка XPI: fuel/030105.md
  - Кабина:
      - Брисачи:
        - Перење на челните светла: cab/185001.md
  - Дополнителна опрема:
    - Безбедносна опрема, алат:
      - Носач за резервно тркало: complementary/190102.md
    - Опрема на влекачот:
      - Петто тркало: complementary/190501.md
  - Кориснички функции:
    - Предупредување на возачот:
      - Низок притисок на масло: user-functions/2201110.md
      - Висока температура на разладната течност: user-functions/2201114.md
      - Ниско ниво на разладна течност: user-functions/2201115.md
      - Отказ на ABS системот на приколката: user-functions/2201124.md
      - Предупредување дека приколката нема ABS: user-functions/2201125.md
      - Дефект на ABS системот на возилото: user-functions/2201126.md
      - Дефект на EBS системот на приколката: user-functions/2201127.md
      - Дефект на EBS системот на возилото: user-functions/2201128.md
      - Низок притисок во задните сопирачки кругови: user-functions/2201187.md
      - Низок притисок во предните сопирачки кругови: user-functions/2201189.md
      - Низок притисок во паркирна сопирачка и приколката: user-functions/2201191.md
      - Дефект на APS системот: user-functions/2201196.md
      - Дефект на ретардерот: user-functions/2201217.md
      - Дефект на менувачот: user-functions/2201218.md
      - Низок притисок за сопирачката на EBS приколка: user-functions/2201259.md
      - Дефект на SMS системот: user-functions/2201283.md
    - Економична работа:
      - Заштита на менувачот: user-functions/2205170.md
    - Надгледување на возилото:
      - Прикажување на опсег на оптимален број на вртежи: user-functions/2210108.md
    - Сопирачка:
      - Сопирање со сопирачка на издувни гасови: user-functions/2220100.md
    - Одржување:
      - Дијагностика во возилото: user-functions/2265173.md
      - A/C функција за одржување: user-functions/2265369.md
    - Безбедност:
      - Ограничување на брзината: user-functions/2270117.md
      - Заштита од превртување: user-functions/2270132.md
    - Заштита од кражба: 
      - Централно забравување: user-functions/2275180.md
    - Контрола нa моторот:
      - Подесување на бројот навртежи со педалата за гас: user-functions/2280119.md
      - Периодично испарување на јагленохидратите: user-functions/2280573.md
      - Контрола на вентилаторот за ладење: user-functions/228098.md
    - Подготовки:
      - Статус на сигналните сијалици: user-functions/2285517.md
      - Станица за мобилен телефон: user-functions/2285544.md
      - Alcolock: user-functions/2285546.md


