site_name: Работилничка документација

#site_url: https://itaseski.github.io/mkdocs-workshop/

theme:
  name: material
  # Changing the colors
  palette:
    primary: green
    accent: light green
  # Changing the fonts
  font:
    text: Roboto
    code: Roboto Mono 
  # Site language
  language: mk
  # Logo
  logo: assets/logo.png
  # Favicon
  favicon: images/favicon.png
  # Icons
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16 
  # Features
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.sections
    #- navigation.indexes 
    - toc.follow
    #- toc.integrate
    - content.tabs.link
    #- header.autohide
    - search.suggest
    - search.highlight
    - search.share    
    #- navigation.expand
    - navigation.top

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  
  

plugins:
  - search:
      lang: mk
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100vh       
       height: auto
       zoomable: true
       draggable: true
       skip_classes: 
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom

  
  


extra_css:
  - stylesheets/extra.css


#repo_url: https://github.com/itaseski/mkdocs-workshop.git

# navigation
nav:
  - Општо:
    - Возило комплет:
      - Поправка на пластични делови: vehicle/000001.md  
      - Складирање на шасии и делови: vehicle/000002.md 
      - Означување: vehicle/000003.md
      - Вибрации: vehicle/000004.md

