site_name: Работилничка документација

site_url: https://itaseski.github.io/mkdocs-workshop/

theme:
  name: material
  palette:
    primary: green

  # Language
  language: mk

plugins:
  - search


extra_css:
  - stylesheets/extra.css

